### ISSUE TITLE
Show/hide spell attributes and summaries when out/in of cat or bear form.  [Feature Request]

### ISSUE THREAD

**Issue by OnceWasPerfect** [raethkcj/RatingBuster#109]
While you're messing around with feral attack power it would be nice if the spell related summaries and breakdowns could hide when in cat/bear form and show when in caster/tree/chicken form.

**Comment by merijn** [comment]
Or, alternatively, add a toggle/hotkey to swap between showing different sets of. I have similar problems on both druid (showing both resto and feral stats) and on warrior (tank vs DPS stats) getting very cluttered, so multiple comparison profiles would be nice.

**Comment by raethkcj** [comment]
The solution I'd probably choose would be to implement [LibDualSpec](https://www.wowace.com/projects/libdualspec-1-0), rather than automatically switching based on forms or providing keybinds.

In the meantime, if you'd like to create your own keybinds, RatingBuster's profiles use [AceDB](https://www.wowace.com/projects/ace3/pages/api/ace-db-3-0), so you could choose to swap between profiles in a macro using something like this:
```lua
/run RatingBuster.db:SetProfile("Shaman")
```

**Comment by merijn** [comment]
tbh, only seeing your active spec is rather limiting in that it makes evaluating offspec gear very tricky. Sometimes I only want to see the healer/caster stats of an item even when I'm in a different spec.
