### ISSUE TITLE
[Bug]: (Wrath Classic) Armor Penetration is not shown

### ISSUE THREAD

**Issue by 10hendersonm** [raethkcj/RatingBuster#112]
### Describe the bug

> Seems to be https://github.com/raethkcj/RatingBuster/issues/111 but on the English locale.

Armor penetration isn't displayed. This looks to be because the word `rating` is omitted from some (all?) tooltips.

Ex:

```diff
  Expected
- Increases your armor penetration rating by 35.
  Actual
+ Increases your armor penetration by 35.
```
https://github.com/raethkcj/RatingBuster/blob/a92eef31dfc54cf523ee8a1248f79899ccc67367/libs/StatLogic/locales/enUS.lua#L467-L469

Humorously, the item ID referenced is the exact ring I'm wearing - the [Ring of Foul Mojo](https://www.wowhead.com/wotlk/item=43178/ring-of-foul-mojo).

![image](https://user-images.githubusercontent.com/14095644/197365635-99917554-8f7e-48df-950e-50497fb79593.png)

![image](https://user-images.githubusercontent.com/14095644/197365641-d99744b5-0f1c-4c59-99d9-297cad790edf.png)

### Addon Source

Curseforge

### Version

3.4.0.22

### Locale

English

### Talent Specialization

Feral Druid

### Race

Tauren

**Comment by raethkcj** [comment]
Thanks! A couple things:

1. Blizzard is actually very inconsistent with many `Equip:` stats, and the word "rating" actually does appear in many of them, e.g. https://www.wowhead.com/wotlk/item=39420/anarchy, so I've added the pattern as a second one rather than replacing the existing one. I do appreciate the pull request, though!

2. I don't host this addon on CurseForge, so if you downloaded it there you're probably actually using this version:  https://github.com/CKNOEP/RatingBuster  
My fork was ported from the 2.4.3 version and maintained throughout TBC Classic; CKNOEP's was just ported recently from the 3.3.5 version.
