### ISSUE TITLE
Armor is converted to x2 attack power in russian locale

### ISSUE THREAD

**Issue by Mard35** [raethkcj/RatingBuster#117]
![WoWScrnShot_110122_015608](https://user-images.githubusercontent.com/61734903/200744292-3efb18d5-de6f-4dda-8480-c0fad5381f3c.jpg)
Hello, why armor is converted to x2 attack power in russian locale? The word "усиление" doesn't mean strength here.

_Originally posted by @Mard35 in https://github.com/raethkcj/RatingBuster/issues/9#issuecomment-1308225691_

**Comment by Mard35** [comment]
> It has to do with a missing declension causing it to match out of order.
> 
> For strength I have:
> 
> ```
> "сила"
> "силу"
> "силе"
> ```
> 
> For armor I only have `"броня"`, can you help with all the other possible declensions of this, or all the other spellings it could appear as in game?

Are you sure you understood me correctly? Armor should not be converted here. Addon sees the part "силе" in word "у**силе**ние". And it converts it to attack power (for warrior). But "у**силе**ние" is not about strength. 

"Броня:" (on gear - always with a capital letter and a colon)
"броню" (on scrolls)
"к броне" (armor enchants on gear)
"брони" (on cosumables and usable trinkets)

You can get this info on wowhead by switching languages.

**Comment by raethkcj** [comment]
I'm sure. The addon matches patterns in order from most specific to least specific. Since there was no pattern for `брони`, it picked the next match, which was `силе`, as you said. By adding the pattern for `брони` it will stop searching for matches.

While I could look through every single item on wowhead, it saves a ton of time to have a native speaker. In English, these are all spelled the same way, so I have no idea which categories of item might use a different spelling. Thank you very much for the list, I'm in a raid now but I'll get them added by the end of the night.
