### ISSUE TITLE
Possible to add stats on comparison tooltip?

### ISSUE THREAD

**Issue by infekSK** [raethkcj/RatingBuster#12]
Hi, I'm sorry for raising an issue for this, wasn't sure how else to contact you. 

Is it possible to have this addon work on the comparison tooltip? For items like rings and weapons it's hard to gauge the actual pro/con of a new item. I have no idea if it's possible, I'm assuming it probably isn't. 

Thanks!

**Comment by raethkcj** [comment]
This feature should have been working already, make sure you have `Display style for diff value` set to Main instead of Compare (it should be Main by default). There was a bug where it only worked for one ring instead of both, but that has been fixed in most recent version.

![image](https://user-images.githubusercontent.com/7716908/141355004-f5f60840-b99b-4491-8512-81657d69401b.png)
