### ISSUE TITLE
Sometimes Ranged AP don't get calculated in summary

### ISSUE THREAD

**Issue by Citano** [raethkcj/RatingBuster#32]
For some reason, Ranged AP does not always get calculated as shown in the example here.
Not sure what triggers it nor how to reproduce.
![image](https://user-images.githubusercontent.com/29778633/122266700-5ccc0900-ceda-11eb-9547-aba8058b0f9e.png)

**Comment by krydd** [comment]
I have seen the same problem for some items as well:
![rap_missing](https://user-images.githubusercontent.com/11898665/122371929-8c255900-cf60-11eb-9ba3-7935e280a866.jpg)

**Comment by aeadio** [comment]
Doesn't just happen for RAP. Happens for multiple stats, including melee AP. There seems to either be a delay in tooltip scanning logic, or it doesn't trigger sometimes. The actual calculation logic doesn't seem to be off, since it will eventually populate the values correctly if you keep trying, and/or reloading.

**Comment by raethkcj** [comment]
Item data aren't guaranteed to exist when you first set a tooltip to an item. RatingBuster caches the first result for performance whether it got any real data or not, so when the data comes in later, RatingBuster is stuck using its old empty cache version. For most of WoW there haven't been clean ways around this, but there are some new ItemMixin APIs since BFA that may help:

https://wowpedia.fandom.com/wiki/ItemMixin

It is odd that it's getting partial stats though, so it's possible there's actually just an issue with one or more of the StatLogic scanners.

**Comment by chefBrian** [comment]
Yeah this is also happening for mele ap. Agility isn't considered at all. Also cannot trigger AP conversion for AGI to be displayed either.

**Comment by raethkcj** [comment]
@chefBrian agi seems like a separate issue, what class and locale?

**Comment by chefBrian** [comment]
@raethkcj my fault - I will create a separate issue
