### ISSUE TITLE
Offhand isn't calculating correctly.

### ISSUE THREAD

**Issue by darkcloud784** [raethkcj/RatingBuster#35]
![image](https://user-images.githubusercontent.com/989990/122659012-cd706100-d138-11eb-9aea-d206912c9a6d.png)

**Comment by darkcloud784** [comment]
@raethkcj No update to this issue? Seems to still happen on 1.0.10.

**Comment by raethkcj** [comment]
All the patterns and calculations are correct, the game just doesn't consistently send data as soon as you mouseover an item.

**Comment by darkcloud784** [comment]
> 
> 
> All the patterns and calculations are correct, the game just doesn't consistently send data as soon as you mouseover an item.

Weird, is there a reason for this?

**Comment by raethkcj** [comment]
Yeah, for items that your client doesn't have cached, the server presumably needs to do a database lookup before responding with the info. The response is async so that neither your client nor the server gets locked. To players this normally looks close to instant but addons can see the empty data. Can probably be fixed for this addon in a couple different ways but I haven't had time to do so yet.

**Comment by darkcloud784** [comment]
> 
> 
> Yeah, for items that your client doesn't have cached, the server presumably needs to do a database lookup before responding with the info. The response is async so that neither your client nor the server gets locked. To players this normally looks close to instant but addons can see the empty data. Can probably be fixed for this addon in a couple different ways but I haven't had time to do so yet.

Thank you for the detailed response and explanation. Hopefully you can get some time to put in the fixes you mentioned.
