### ISSUE TITLE
Stats summary shows all zeroes

### ISSUE THREAD

**Issue by Krelln** [raethkcj/RatingBuster#51]
Hello!
All my stats summary shows 0 (+0) while I'm comparing items. Without enabled option to show zeroes, there is no stats summary at all.
![AddonIssue](https://user-images.githubusercontent.com/28108805/132739811-23d1e317-a789-4720-9953-f8781f345ae7.png)
I use Russian game client, so maybe localization caused this problem,
Tried to disable all other addons and nothing changed.
Thank you

**Comment by raethkcj** [comment]
Hello, I'm sorry it took so long to respond here, but significant improvements have been made to the Russian localizations thanks to work done in #9. Since the work there is still ongoing, I'm going to close this issue for now.

![image](https://user-images.githubusercontent.com/7716908/192102871-493f9b22-9fcf-4a77-b8ac-b9bd9a54c2a9.png)
