### ISSUE TITLE
Hard crash to desktop when socketing gems

### ISSUE THREAD

**Issue by mykkenny** [raethkcj/RatingBuster#94]
As per title. I have disabled all other addons. 

![ratingBusterCrash](https://user-images.githubusercontent.com/10851369/189726455-1634e03b-0157-4297-bdd4-5feb57bff27e.png)

I am adding a Jagged Seaspray Emerald to  my mages Brutal Gladiator's Silk Amice, however it occurred with other gems in other sockets, on other characters.

**Comment by raethkcj** [comment]
Are you by chance getting RatingBuster from Curseforge? https://www.curseforge.com/wow/addons/ratingbuster-wotlk-classic

If so, that's not this repo, that's https://github.com/CKNOEP/RatingBuster.

I only ask because I've never seen this issue with my version but saw it mentioned in the comments there.

**Comment by mykkenny** [comment]
Ah, you're right - don't know how I ended up there, when I meant to download yours in the first place!

**Comment by raethkcj** [comment]
Sounds good, thank you. I think I'll make an issue template that will hopefully encourage people to post where they got the addon to cut down on the confusion.
